[functions]
  node_bundler = "esbuild"
  directory = "functions/"
  included_files = ["./db/**.json"]

[dev]
  port = 3000
  publish = "dist"

 # [[redirects]]
 # from = "/api/todos"
 # to = "/.netlify/functions/todos"
 # status = 200

 # [[redirects]]
 # from = "/"
 # to = "/index.html"
 # status = 200

  #  [[redirects]]
  # from = "/todolist"
  # to = "/todolist.html"
  # status = 200

  #   [[redirects]]
  # from = "/todolist.html"
  # to = "/todolist.html"
  # status = 200